/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GitProviderRemoveRequest,
  InlineObject,
} from '../models/index';
import {
    GitProviderRemoveRequestFromJSON,
    GitProviderRemoveRequestToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/index';

export interface GitProviderRemoveOperationRequest {
    gitProviderRemoveRequest: GitProviderRemoveRequest;
}

/**
 * 
 */
export class GitProviderApi extends runtime.BaseAPI {

    /**
     */
    async gitProviderGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }


        let urlPath = `/gitProvider.getAll`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async gitProviderGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gitProviderGetAllRaw(initOverrides);
    }

    /**
     */
    async gitProviderRemoveRaw(requestParameters: GitProviderRemoveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['gitProviderRemoveRequest'] == null) {
            throw new runtime.RequiredError(
                'gitProviderRemoveRequest',
                'Required parameter "gitProviderRemoveRequest" was null or undefined when calling gitProviderRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // apiKey authentication
        }


        let urlPath = `/gitProvider.remove`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GitProviderRemoveRequestToJSON(requestParameters['gitProviderRemoveRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async gitProviderRemove(requestParameters: GitProviderRemoveOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.gitProviderRemoveRaw(requestParameters, initOverrides);
    }

}
