/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSetupMonitoringRequestMetricsConfigContainers } from './AdminSetupMonitoringRequestMetricsConfigContainers';
import {
    AdminSetupMonitoringRequestMetricsConfigContainersFromJSON,
    AdminSetupMonitoringRequestMetricsConfigContainersFromJSONTyped,
    AdminSetupMonitoringRequestMetricsConfigContainersToJSON,
    AdminSetupMonitoringRequestMetricsConfigContainersToJSONTyped,
} from './AdminSetupMonitoringRequestMetricsConfigContainers';
import type { AdminSetupMonitoringRequestMetricsConfigServer } from './AdminSetupMonitoringRequestMetricsConfigServer';
import {
    AdminSetupMonitoringRequestMetricsConfigServerFromJSON,
    AdminSetupMonitoringRequestMetricsConfigServerFromJSONTyped,
    AdminSetupMonitoringRequestMetricsConfigServerToJSON,
    AdminSetupMonitoringRequestMetricsConfigServerToJSONTyped,
} from './AdminSetupMonitoringRequestMetricsConfigServer';

/**
 * 
 * @export
 * @interface AdminSetupMonitoringRequestMetricsConfig
 */
export interface AdminSetupMonitoringRequestMetricsConfig {
    /**
     * 
     * @type {AdminSetupMonitoringRequestMetricsConfigServer}
     * @memberof AdminSetupMonitoringRequestMetricsConfig
     */
    server: AdminSetupMonitoringRequestMetricsConfigServer;
    /**
     * 
     * @type {AdminSetupMonitoringRequestMetricsConfigContainers}
     * @memberof AdminSetupMonitoringRequestMetricsConfig
     */
    containers: AdminSetupMonitoringRequestMetricsConfigContainers;
}

/**
 * Check if a given object implements the AdminSetupMonitoringRequestMetricsConfig interface.
 */
export function instanceOfAdminSetupMonitoringRequestMetricsConfig(value: object): value is AdminSetupMonitoringRequestMetricsConfig {
    if (!('server' in value) || value['server'] === undefined) return false;
    if (!('containers' in value) || value['containers'] === undefined) return false;
    return true;
}

export function AdminSetupMonitoringRequestMetricsConfigFromJSON(json: any): AdminSetupMonitoringRequestMetricsConfig {
    return AdminSetupMonitoringRequestMetricsConfigFromJSONTyped(json, false);
}

export function AdminSetupMonitoringRequestMetricsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSetupMonitoringRequestMetricsConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'server': AdminSetupMonitoringRequestMetricsConfigServerFromJSON(json['server']),
        'containers': AdminSetupMonitoringRequestMetricsConfigContainersFromJSON(json['containers']),
    };
}

export function AdminSetupMonitoringRequestMetricsConfigToJSON(json: any): AdminSetupMonitoringRequestMetricsConfig {
    return AdminSetupMonitoringRequestMetricsConfigToJSONTyped(json, false);
}

export function AdminSetupMonitoringRequestMetricsConfigToJSONTyped(value?: AdminSetupMonitoringRequestMetricsConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'server': AdminSetupMonitoringRequestMetricsConfigServerToJSON(value['server']),
        'containers': AdminSetupMonitoringRequestMetricsConfigContainersToJSON(value['containers']),
    };
}

