/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSetupMonitoringRequestMetricsConfigServerThresholds } from './AdminSetupMonitoringRequestMetricsConfigServerThresholds';
import {
    AdminSetupMonitoringRequestMetricsConfigServerThresholdsFromJSON,
    AdminSetupMonitoringRequestMetricsConfigServerThresholdsFromJSONTyped,
    AdminSetupMonitoringRequestMetricsConfigServerThresholdsToJSON,
    AdminSetupMonitoringRequestMetricsConfigServerThresholdsToJSONTyped,
} from './AdminSetupMonitoringRequestMetricsConfigServerThresholds';

/**
 * 
 * @export
 * @interface AdminSetupMonitoringRequestMetricsConfigServer
 */
export interface AdminSetupMonitoringRequestMetricsConfigServer {
    /**
     * 
     * @type {number}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    refreshRate: number;
    /**
     * 
     * @type {number}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    urlCallback: string;
    /**
     * 
     * @type {number}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    retentionDays: number;
    /**
     * 
     * @type {string}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    cronJob: string;
    /**
     * 
     * @type {AdminSetupMonitoringRequestMetricsConfigServerThresholds}
     * @memberof AdminSetupMonitoringRequestMetricsConfigServer
     */
    thresholds: AdminSetupMonitoringRequestMetricsConfigServerThresholds;
}

/**
 * Check if a given object implements the AdminSetupMonitoringRequestMetricsConfigServer interface.
 */
export function instanceOfAdminSetupMonitoringRequestMetricsConfigServer(value: object): value is AdminSetupMonitoringRequestMetricsConfigServer {
    if (!('refreshRate' in value) || value['refreshRate'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('urlCallback' in value) || value['urlCallback'] === undefined) return false;
    if (!('retentionDays' in value) || value['retentionDays'] === undefined) return false;
    if (!('cronJob' in value) || value['cronJob'] === undefined) return false;
    if (!('thresholds' in value) || value['thresholds'] === undefined) return false;
    return true;
}

export function AdminSetupMonitoringRequestMetricsConfigServerFromJSON(json: any): AdminSetupMonitoringRequestMetricsConfigServer {
    return AdminSetupMonitoringRequestMetricsConfigServerFromJSONTyped(json, false);
}

export function AdminSetupMonitoringRequestMetricsConfigServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSetupMonitoringRequestMetricsConfigServer {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshRate': json['refreshRate'],
        'port': json['port'],
        'token': json['token'],
        'urlCallback': json['urlCallback'],
        'retentionDays': json['retentionDays'],
        'cronJob': json['cronJob'],
        'thresholds': AdminSetupMonitoringRequestMetricsConfigServerThresholdsFromJSON(json['thresholds']),
    };
}

export function AdminSetupMonitoringRequestMetricsConfigServerToJSON(json: any): AdminSetupMonitoringRequestMetricsConfigServer {
    return AdminSetupMonitoringRequestMetricsConfigServerToJSONTyped(json, false);
}

export function AdminSetupMonitoringRequestMetricsConfigServerToJSONTyped(value?: AdminSetupMonitoringRequestMetricsConfigServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshRate': value['refreshRate'],
        'port': value['port'],
        'token': value['token'],
        'urlCallback': value['urlCallback'],
        'retentionDays': value['retentionDays'],
        'cronJob': value['cronJob'],
        'thresholds': AdminSetupMonitoringRequestMetricsConfigServerThresholdsToJSON(value['thresholds']),
    };
}

