/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminSetupMonitoringRequestMetricsConfigContainersServices } from './AdminSetupMonitoringRequestMetricsConfigContainersServices';
import {
    AdminSetupMonitoringRequestMetricsConfigContainersServicesFromJSON,
    AdminSetupMonitoringRequestMetricsConfigContainersServicesFromJSONTyped,
    AdminSetupMonitoringRequestMetricsConfigContainersServicesToJSON,
    AdminSetupMonitoringRequestMetricsConfigContainersServicesToJSONTyped,
} from './AdminSetupMonitoringRequestMetricsConfigContainersServices';

/**
 * 
 * @export
 * @interface AdminSetupMonitoringRequestMetricsConfigContainers
 */
export interface AdminSetupMonitoringRequestMetricsConfigContainers {
    /**
     * 
     * @type {number}
     * @memberof AdminSetupMonitoringRequestMetricsConfigContainers
     */
    refreshRate: number;
    /**
     * 
     * @type {AdminSetupMonitoringRequestMetricsConfigContainersServices}
     * @memberof AdminSetupMonitoringRequestMetricsConfigContainers
     */
    services: AdminSetupMonitoringRequestMetricsConfigContainersServices;
}

/**
 * Check if a given object implements the AdminSetupMonitoringRequestMetricsConfigContainers interface.
 */
export function instanceOfAdminSetupMonitoringRequestMetricsConfigContainers(value: object): value is AdminSetupMonitoringRequestMetricsConfigContainers {
    if (!('refreshRate' in value) || value['refreshRate'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    return true;
}

export function AdminSetupMonitoringRequestMetricsConfigContainersFromJSON(json: any): AdminSetupMonitoringRequestMetricsConfigContainers {
    return AdminSetupMonitoringRequestMetricsConfigContainersFromJSONTyped(json, false);
}

export function AdminSetupMonitoringRequestMetricsConfigContainersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminSetupMonitoringRequestMetricsConfigContainers {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshRate': json['refreshRate'],
        'services': AdminSetupMonitoringRequestMetricsConfigContainersServicesFromJSON(json['services']),
    };
}

export function AdminSetupMonitoringRequestMetricsConfigContainersToJSON(json: any): AdminSetupMonitoringRequestMetricsConfigContainers {
    return AdminSetupMonitoringRequestMetricsConfigContainersToJSONTyped(json, false);
}

export function AdminSetupMonitoringRequestMetricsConfigContainersToJSONTyped(value?: AdminSetupMonitoringRequestMetricsConfigContainers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshRate': value['refreshRate'],
        'services': AdminSetupMonitoringRequestMetricsConfigContainersServicesToJSON(value['services']),
    };
}

