/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiDeployRequestConfigFilesInner
 */
export interface AiDeployRequestConfigFilesInner {
    /**
     * 
     * @type {string}
     * @memberof AiDeployRequestConfigFilesInner
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof AiDeployRequestConfigFilesInner
     */
    content: string;
}

/**
 * Check if a given object implements the AiDeployRequestConfigFilesInner interface.
 */
export function instanceOfAiDeployRequestConfigFilesInner(value: object): value is AiDeployRequestConfigFilesInner {
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function AiDeployRequestConfigFilesInnerFromJSON(json: any): AiDeployRequestConfigFilesInner {
    return AiDeployRequestConfigFilesInnerFromJSONTyped(json, false);
}

export function AiDeployRequestConfigFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiDeployRequestConfigFilesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'filePath': json['filePath'],
        'content': json['content'],
    };
}

export function AiDeployRequestConfigFilesInnerToJSON(json: any): AiDeployRequestConfigFilesInner {
    return AiDeployRequestConfigFilesInnerToJSONTyped(json, false);
}

export function AiDeployRequestConfigFilesInnerToJSONTyped(value?: AiDeployRequestConfigFilesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filePath': value['filePath'],
        'content': value['content'],
    };
}

