/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiDeployRequestDomainsInner
 */
export interface AiDeployRequestDomainsInner {
    /**
     * 
     * @type {string}
     * @memberof AiDeployRequestDomainsInner
     */
    host: string;
    /**
     * 
     * @type {number}
     * @memberof AiDeployRequestDomainsInner
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof AiDeployRequestDomainsInner
     */
    serviceName: string;
}

/**
 * Check if a given object implements the AiDeployRequestDomainsInner interface.
 */
export function instanceOfAiDeployRequestDomainsInner(value: object): value is AiDeployRequestDomainsInner {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    return true;
}

export function AiDeployRequestDomainsInnerFromJSON(json: any): AiDeployRequestDomainsInner {
    return AiDeployRequestDomainsInnerFromJSONTyped(json, false);
}

export function AiDeployRequestDomainsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiDeployRequestDomainsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'port': json['port'],
        'serviceName': json['serviceName'],
    };
}

export function AiDeployRequestDomainsInnerToJSON(json: any): AiDeployRequestDomainsInner {
    return AiDeployRequestDomainsInnerToJSONTyped(json, false);
}

export function AiDeployRequestDomainsInnerToJSONTyped(value?: AiDeployRequestDomainsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'port': value['port'],
        'serviceName': value['serviceName'],
    };
}

