/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationUpdateRequestModeSwarmReplicatedJob } from './ApplicationUpdateRequestModeSwarmReplicatedJob';
import {
    ApplicationUpdateRequestModeSwarmReplicatedJobFromJSON,
    ApplicationUpdateRequestModeSwarmReplicatedJobFromJSONTyped,
    ApplicationUpdateRequestModeSwarmReplicatedJobToJSON,
    ApplicationUpdateRequestModeSwarmReplicatedJobToJSONTyped,
} from './ApplicationUpdateRequestModeSwarmReplicatedJob';
import type { ApplicationUpdateRequestModeSwarmReplicated } from './ApplicationUpdateRequestModeSwarmReplicated';
import {
    ApplicationUpdateRequestModeSwarmReplicatedFromJSON,
    ApplicationUpdateRequestModeSwarmReplicatedFromJSONTyped,
    ApplicationUpdateRequestModeSwarmReplicatedToJSON,
    ApplicationUpdateRequestModeSwarmReplicatedToJSONTyped,
} from './ApplicationUpdateRequestModeSwarmReplicated';

/**
 * 
 * @export
 * @interface ApplicationUpdateRequestModeSwarm
 */
export interface ApplicationUpdateRequestModeSwarm {
    /**
     * 
     * @type {ApplicationUpdateRequestModeSwarmReplicated}
     * @memberof ApplicationUpdateRequestModeSwarm
     */
    replicated?: ApplicationUpdateRequestModeSwarmReplicated;
    /**
     * 
     * @type {object}
     * @memberof ApplicationUpdateRequestModeSwarm
     */
    global?: object;
    /**
     * 
     * @type {ApplicationUpdateRequestModeSwarmReplicatedJob}
     * @memberof ApplicationUpdateRequestModeSwarm
     */
    replicatedJob?: ApplicationUpdateRequestModeSwarmReplicatedJob;
    /**
     * 
     * @type {object}
     * @memberof ApplicationUpdateRequestModeSwarm
     */
    globalJob?: object;
}

/**
 * Check if a given object implements the ApplicationUpdateRequestModeSwarm interface.
 */
export function instanceOfApplicationUpdateRequestModeSwarm(value: object): value is ApplicationUpdateRequestModeSwarm {
    return true;
}

export function ApplicationUpdateRequestModeSwarmFromJSON(json: any): ApplicationUpdateRequestModeSwarm {
    return ApplicationUpdateRequestModeSwarmFromJSONTyped(json, false);
}

export function ApplicationUpdateRequestModeSwarmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationUpdateRequestModeSwarm {
    if (json == null) {
        return json;
    }
    return {
        
        'replicated': json['Replicated'] == null ? undefined : ApplicationUpdateRequestModeSwarmReplicatedFromJSON(json['Replicated']),
        'global': json['Global'] == null ? undefined : json['Global'],
        'replicatedJob': json['ReplicatedJob'] == null ? undefined : ApplicationUpdateRequestModeSwarmReplicatedJobFromJSON(json['ReplicatedJob']),
        'globalJob': json['GlobalJob'] == null ? undefined : json['GlobalJob'],
    };
}

export function ApplicationUpdateRequestModeSwarmToJSON(json: any): ApplicationUpdateRequestModeSwarm {
    return ApplicationUpdateRequestModeSwarmToJSONTyped(json, false);
}

export function ApplicationUpdateRequestModeSwarmToJSONTyped(value?: ApplicationUpdateRequestModeSwarm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Replicated': ApplicationUpdateRequestModeSwarmReplicatedToJSON(value['replicated']),
        'Global': value['global'],
        'ReplicatedJob': ApplicationUpdateRequestModeSwarmReplicatedJobToJSON(value['replicatedJob']),
        'GlobalJob': value['globalJob'],
    };
}

