/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationSaveGitProdiverRequest
 */
export interface ApplicationSaveGitProdiverRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    customGitBranch?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    applicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    customGitBuildPath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    customGitUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    watchPaths?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    enableSubmodules: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationSaveGitProdiverRequest
     */
    customGitSSHKeyId?: string | null;
}

/**
 * Check if a given object implements the ApplicationSaveGitProdiverRequest interface.
 */
export function instanceOfApplicationSaveGitProdiverRequest(value: object): value is ApplicationSaveGitProdiverRequest {
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    if (!('enableSubmodules' in value) || value['enableSubmodules'] === undefined) return false;
    return true;
}

export function ApplicationSaveGitProdiverRequestFromJSON(json: any): ApplicationSaveGitProdiverRequest {
    return ApplicationSaveGitProdiverRequestFromJSONTyped(json, false);
}

export function ApplicationSaveGitProdiverRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationSaveGitProdiverRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customGitBranch': json['customGitBranch'] == null ? undefined : json['customGitBranch'],
        'applicationId': json['applicationId'],
        'customGitBuildPath': json['customGitBuildPath'] == null ? undefined : json['customGitBuildPath'],
        'customGitUrl': json['customGitUrl'] == null ? undefined : json['customGitUrl'],
        'watchPaths': json['watchPaths'] == null ? undefined : json['watchPaths'],
        'enableSubmodules': json['enableSubmodules'],
        'customGitSSHKeyId': json['customGitSSHKeyId'] == null ? undefined : json['customGitSSHKeyId'],
    };
}

export function ApplicationSaveGitProdiverRequestToJSON(json: any): ApplicationSaveGitProdiverRequest {
    return ApplicationSaveGitProdiverRequestToJSONTyped(json, false);
}

export function ApplicationSaveGitProdiverRequestToJSONTyped(value?: ApplicationSaveGitProdiverRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customGitBranch': value['customGitBranch'],
        'applicationId': value['applicationId'],
        'customGitBuildPath': value['customGitBuildPath'],
        'customGitUrl': value['customGitUrl'],
        'watchPaths': value['watchPaths'],
        'enableSubmodules': value['enableSubmodules'],
        'customGitSSHKeyId': value['customGitSSHKeyId'],
    };
}

