/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApplicationUpdateRequestPlacementSwarmPlatformsInner } from './ApplicationUpdateRequestPlacementSwarmPlatformsInner';
import {
    ApplicationUpdateRequestPlacementSwarmPlatformsInnerFromJSON,
    ApplicationUpdateRequestPlacementSwarmPlatformsInnerFromJSONTyped,
    ApplicationUpdateRequestPlacementSwarmPlatformsInnerToJSON,
    ApplicationUpdateRequestPlacementSwarmPlatformsInnerToJSONTyped,
} from './ApplicationUpdateRequestPlacementSwarmPlatformsInner';
import type { ApplicationUpdateRequestPlacementSwarmPreferencesInner } from './ApplicationUpdateRequestPlacementSwarmPreferencesInner';
import {
    ApplicationUpdateRequestPlacementSwarmPreferencesInnerFromJSON,
    ApplicationUpdateRequestPlacementSwarmPreferencesInnerFromJSONTyped,
    ApplicationUpdateRequestPlacementSwarmPreferencesInnerToJSON,
    ApplicationUpdateRequestPlacementSwarmPreferencesInnerToJSONTyped,
} from './ApplicationUpdateRequestPlacementSwarmPreferencesInner';

/**
 * 
 * @export
 * @interface ApplicationUpdateRequestPlacementSwarm
 */
export interface ApplicationUpdateRequestPlacementSwarm {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationUpdateRequestPlacementSwarm
     */
    constraints?: Array<string>;
    /**
     * 
     * @type {Array<ApplicationUpdateRequestPlacementSwarmPreferencesInner>}
     * @memberof ApplicationUpdateRequestPlacementSwarm
     */
    preferences?: Array<ApplicationUpdateRequestPlacementSwarmPreferencesInner>;
    /**
     * 
     * @type {number}
     * @memberof ApplicationUpdateRequestPlacementSwarm
     */
    maxReplicas?: number;
    /**
     * 
     * @type {Array<ApplicationUpdateRequestPlacementSwarmPlatformsInner>}
     * @memberof ApplicationUpdateRequestPlacementSwarm
     */
    platforms?: Array<ApplicationUpdateRequestPlacementSwarmPlatformsInner>;
}

/**
 * Check if a given object implements the ApplicationUpdateRequestPlacementSwarm interface.
 */
export function instanceOfApplicationUpdateRequestPlacementSwarm(value: object): value is ApplicationUpdateRequestPlacementSwarm {
    return true;
}

export function ApplicationUpdateRequestPlacementSwarmFromJSON(json: any): ApplicationUpdateRequestPlacementSwarm {
    return ApplicationUpdateRequestPlacementSwarmFromJSONTyped(json, false);
}

export function ApplicationUpdateRequestPlacementSwarmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationUpdateRequestPlacementSwarm {
    if (json == null) {
        return json;
    }
    return {
        
        'constraints': json['Constraints'] == null ? undefined : json['Constraints'],
        'preferences': json['Preferences'] == null ? undefined : ((json['Preferences'] as Array<any>).map(ApplicationUpdateRequestPlacementSwarmPreferencesInnerFromJSON)),
        'maxReplicas': json['MaxReplicas'] == null ? undefined : json['MaxReplicas'],
        'platforms': json['Platforms'] == null ? undefined : ((json['Platforms'] as Array<any>).map(ApplicationUpdateRequestPlacementSwarmPlatformsInnerFromJSON)),
    };
}

export function ApplicationUpdateRequestPlacementSwarmToJSON(json: any): ApplicationUpdateRequestPlacementSwarm {
    return ApplicationUpdateRequestPlacementSwarmToJSONTyped(json, false);
}

export function ApplicationUpdateRequestPlacementSwarmToJSONTyped(value?: ApplicationUpdateRequestPlacementSwarm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Constraints': value['constraints'],
        'Preferences': value['preferences'] == null ? undefined : ((value['preferences'] as Array<any>).map(ApplicationUpdateRequestPlacementSwarmPreferencesInnerToJSON)),
        'MaxReplicas': value['maxReplicas'],
        'Platforms': value['platforms'] == null ? undefined : ((value['platforms'] as Array<any>).map(ApplicationUpdateRequestPlacementSwarmPlatformsInnerToJSON)),
    };
}

