/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationMoveRequest
 */
export interface ApplicationMoveRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationMoveRequest
     */
    applicationId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationMoveRequest
     */
    targetProjectId: string;
}

/**
 * Check if a given object implements the ApplicationMoveRequest interface.
 */
export function instanceOfApplicationMoveRequest(value: object): value is ApplicationMoveRequest {
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    if (!('targetProjectId' in value) || value['targetProjectId'] === undefined) return false;
    return true;
}

export function ApplicationMoveRequestFromJSON(json: any): ApplicationMoveRequest {
    return ApplicationMoveRequestFromJSONTyped(json, false);
}

export function ApplicationMoveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationMoveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['applicationId'],
        'targetProjectId': json['targetProjectId'],
    };
}

export function ApplicationMoveRequestToJSON(json: any): ApplicationMoveRequest {
    return ApplicationMoveRequestToJSONTyped(json, false);
}

export function ApplicationMoveRequestToJSONTyped(value?: ApplicationMoveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationId': value['applicationId'],
        'targetProjectId': value['targetProjectId'],
    };
}

