/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationDeleteRequest
 */
export interface ApplicationDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationDeleteRequest
     */
    applicationId: string;
}

/**
 * Check if a given object implements the ApplicationDeleteRequest interface.
 */
export function instanceOfApplicationDeleteRequest(value: object): value is ApplicationDeleteRequest {
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    return true;
}

export function ApplicationDeleteRequestFromJSON(json: any): ApplicationDeleteRequest {
    return ApplicationDeleteRequestFromJSONTyped(json, false);
}

export function ApplicationDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['applicationId'],
    };
}

export function ApplicationDeleteRequestToJSON(json: any): ApplicationDeleteRequest {
    return ApplicationDeleteRequestToJSONTyped(json, false);
}

export function ApplicationDeleteRequestToJSONTyped(value?: ApplicationDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationId': value['applicationId'],
    };
}

