/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicationCreateRequest
 */
export interface ApplicationCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    appName?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationCreateRequest
     */
    serverId?: string | null;
}

/**
 * Check if a given object implements the ApplicationCreateRequest interface.
 */
export function instanceOfApplicationCreateRequest(value: object): value is ApplicationCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    return true;
}

export function ApplicationCreateRequestFromJSON(json: any): ApplicationCreateRequest {
    return ApplicationCreateRequestFromJSONTyped(json, false);
}

export function ApplicationCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'description': json['description'] == null ? undefined : json['description'],
        'projectId': json['projectId'],
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
    };
}

export function ApplicationCreateRequestToJSON(json: any): ApplicationCreateRequest {
    return ApplicationCreateRequestToJSONTyped(json, false);
}

export function ApplicationCreateRequestToJSONTyped(value?: ApplicationCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'appName': value['appName'],
        'description': value['description'],
        'projectId': value['projectId'],
        'serverId': value['serverId'],
    };
}

