/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComposeMoveRequest
 */
export interface ComposeMoveRequest {
    /**
     * 
     * @type {string}
     * @memberof ComposeMoveRequest
     */
    composeId: string;
    /**
     * 
     * @type {string}
     * @memberof ComposeMoveRequest
     */
    targetProjectId: string;
}

/**
 * Check if a given object implements the ComposeMoveRequest interface.
 */
export function instanceOfComposeMoveRequest(value: object): value is ComposeMoveRequest {
    if (!('composeId' in value) || value['composeId'] === undefined) return false;
    if (!('targetProjectId' in value) || value['targetProjectId'] === undefined) return false;
    return true;
}

export function ComposeMoveRequestFromJSON(json: any): ComposeMoveRequest {
    return ComposeMoveRequestFromJSONTyped(json, false);
}

export function ComposeMoveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComposeMoveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'composeId': json['composeId'],
        'targetProjectId': json['targetProjectId'],
    };
}

export function ComposeMoveRequestToJSON(json: any): ComposeMoveRequest {
    return ComposeMoveRequestToJSONTyped(json, false);
}

export function ComposeMoveRequestToJSONTyped(value?: ComposeMoveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'composeId': value['composeId'],
        'targetProjectId': value['targetProjectId'],
    };
}

