/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComposeRandomizeComposeRequest
 */
export interface ComposeRandomizeComposeRequest {
    /**
     * 
     * @type {string}
     * @memberof ComposeRandomizeComposeRequest
     */
    composeId: string;
    /**
     * 
     * @type {string}
     * @memberof ComposeRandomizeComposeRequest
     */
    suffix?: string;
}

/**
 * Check if a given object implements the ComposeRandomizeComposeRequest interface.
 */
export function instanceOfComposeRandomizeComposeRequest(value: object): value is ComposeRandomizeComposeRequest {
    if (!('composeId' in value) || value['composeId'] === undefined) return false;
    return true;
}

export function ComposeRandomizeComposeRequestFromJSON(json: any): ComposeRandomizeComposeRequest {
    return ComposeRandomizeComposeRequestFromJSONTyped(json, false);
}

export function ComposeRandomizeComposeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComposeRandomizeComposeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'composeId': json['composeId'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
    };
}

export function ComposeRandomizeComposeRequestToJSON(json: any): ComposeRandomizeComposeRequest {
    return ComposeRandomizeComposeRequestToJSONTyped(json, false);
}

export function ComposeRandomizeComposeRequestToJSONTyped(value?: ComposeRandomizeComposeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'composeId': value['composeId'],
        'suffix': value['suffix'],
    };
}

