/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComposeProcessTemplateRequest
 */
export interface ComposeProcessTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof ComposeProcessTemplateRequest
     */
    base64: string;
    /**
     * 
     * @type {string}
     * @memberof ComposeProcessTemplateRequest
     */
    composeId: string;
}

/**
 * Check if a given object implements the ComposeProcessTemplateRequest interface.
 */
export function instanceOfComposeProcessTemplateRequest(value: object): value is ComposeProcessTemplateRequest {
    if (!('base64' in value) || value['base64'] === undefined) return false;
    if (!('composeId' in value) || value['composeId'] === undefined) return false;
    return true;
}

export function ComposeProcessTemplateRequestFromJSON(json: any): ComposeProcessTemplateRequest {
    return ComposeProcessTemplateRequestFromJSONTyped(json, false);
}

export function ComposeProcessTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComposeProcessTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'base64': json['base64'],
        'composeId': json['composeId'],
    };
}

export function ComposeProcessTemplateRequestToJSON(json: any): ComposeProcessTemplateRequest {
    return ComposeProcessTemplateRequestToJSONTyped(json, false);
}

export function ComposeProcessTemplateRequestToJSONTyped(value?: ComposeProcessTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base64': value['base64'],
        'composeId': value['composeId'],
    };
}

