/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComposeDeleteRequest
 */
export interface ComposeDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof ComposeDeleteRequest
     */
    composeId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComposeDeleteRequest
     */
    deleteVolumes: boolean;
}

/**
 * Check if a given object implements the ComposeDeleteRequest interface.
 */
export function instanceOfComposeDeleteRequest(value: object): value is ComposeDeleteRequest {
    if (!('composeId' in value) || value['composeId'] === undefined) return false;
    if (!('deleteVolumes' in value) || value['deleteVolumes'] === undefined) return false;
    return true;
}

export function ComposeDeleteRequestFromJSON(json: any): ComposeDeleteRequest {
    return ComposeDeleteRequestFromJSONTyped(json, false);
}

export function ComposeDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComposeDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'composeId': json['composeId'],
        'deleteVolumes': json['deleteVolumes'],
    };
}

export function ComposeDeleteRequestToJSON(json: any): ComposeDeleteRequest {
    return ComposeDeleteRequestToJSONTyped(json, false);
}

export function ComposeDeleteRequestToJSONTyped(value?: ComposeDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'composeId': value['composeId'],
        'deleteVolumes': value['deleteVolumes'],
    };
}

