/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DestinationUpdateRequest
 */
export interface DestinationUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    accessKey: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    bucket: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    secretAccessKey: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    destinationId: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    provider: string | null;
    /**
     * 
     * @type {string}
     * @memberof DestinationUpdateRequest
     */
    serverId?: string;
}

/**
 * Check if a given object implements the DestinationUpdateRequest interface.
 */
export function instanceOfDestinationUpdateRequest(value: object): value is DestinationUpdateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('accessKey' in value) || value['accessKey'] === undefined) return false;
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('secretAccessKey' in value) || value['secretAccessKey'] === undefined) return false;
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function DestinationUpdateRequestFromJSON(json: any): DestinationUpdateRequest {
    return DestinationUpdateRequestFromJSONTyped(json, false);
}

export function DestinationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'accessKey': json['accessKey'],
        'bucket': json['bucket'],
        'region': json['region'],
        'endpoint': json['endpoint'],
        'secretAccessKey': json['secretAccessKey'],
        'destinationId': json['destinationId'],
        'provider': json['provider'],
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
    };
}

export function DestinationUpdateRequestToJSON(json: any): DestinationUpdateRequest {
    return DestinationUpdateRequestToJSONTyped(json, false);
}

export function DestinationUpdateRequestToJSONTyped(value?: DestinationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'accessKey': value['accessKey'],
        'bucket': value['bucket'],
        'region': value['region'],
        'endpoint': value['endpoint'],
        'secretAccessKey': value['secretAccessKey'],
        'destinationId': value['destinationId'],
        'provider': value['provider'],
        'serverId': value['serverId'],
    };
}

