/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainValidateDomainRequest
 */
export interface DomainValidateDomainRequest {
    /**
     * 
     * @type {string}
     * @memberof DomainValidateDomainRequest
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof DomainValidateDomainRequest
     */
    serverIp?: string;
}

/**
 * Check if a given object implements the DomainValidateDomainRequest interface.
 */
export function instanceOfDomainValidateDomainRequest(value: object): value is DomainValidateDomainRequest {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function DomainValidateDomainRequestFromJSON(json: any): DomainValidateDomainRequest {
    return DomainValidateDomainRequestFromJSONTyped(json, false);
}

export function DomainValidateDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainValidateDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'serverIp': json['serverIp'] == null ? undefined : json['serverIp'],
    };
}

export function DomainValidateDomainRequestToJSON(json: any): DomainValidateDomainRequest {
    return DomainValidateDomainRequestToJSONTyped(json, false);
}

export function DomainValidateDomainRequestToJSONTyped(value?: DomainValidateDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'serverIp': value['serverIp'],
    };
}

