/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GiteaTestConnectionRequest
 */
export interface GiteaTestConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof GiteaTestConnectionRequest
     */
    giteaId?: string;
    /**
     * 
     * @type {string}
     * @memberof GiteaTestConnectionRequest
     */
    organizationName?: string;
}

/**
 * Check if a given object implements the GiteaTestConnectionRequest interface.
 */
export function instanceOfGiteaTestConnectionRequest(value: object): value is GiteaTestConnectionRequest {
    return true;
}

export function GiteaTestConnectionRequestFromJSON(json: any): GiteaTestConnectionRequest {
    return GiteaTestConnectionRequestFromJSONTyped(json, false);
}

export function GiteaTestConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GiteaTestConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'giteaId': json['giteaId'] == null ? undefined : json['giteaId'],
        'organizationName': json['organizationName'] == null ? undefined : json['organizationName'],
    };
}

export function GiteaTestConnectionRequestToJSON(json: any): GiteaTestConnectionRequest {
    return GiteaTestConnectionRequestToJSONTyped(json, false);
}

export function GiteaTestConnectionRequestToJSONTyped(value?: GiteaTestConnectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'giteaId': value['giteaId'],
        'organizationName': value['organizationName'],
    };
}

