/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MariadbCreateRequest
 */
export interface MariadbCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    appName: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    dockerImage?: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    databaseRootPassword: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    databaseName: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    databaseUser: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    databasePassword: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbCreateRequest
     */
    serverId?: string | null;
}

/**
 * Check if a given object implements the MariadbCreateRequest interface.
 */
export function instanceOfMariadbCreateRequest(value: object): value is MariadbCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('appName' in value) || value['appName'] === undefined) return false;
    if (!('databaseRootPassword' in value) || value['databaseRootPassword'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('databaseName' in value) || value['databaseName'] === undefined) return false;
    if (!('databaseUser' in value) || value['databaseUser'] === undefined) return false;
    if (!('databasePassword' in value) || value['databasePassword'] === undefined) return false;
    return true;
}

export function MariadbCreateRequestFromJSON(json: any): MariadbCreateRequest {
    return MariadbCreateRequestFromJSONTyped(json, false);
}

export function MariadbCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MariadbCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'appName': json['appName'],
        'dockerImage': json['dockerImage'] == null ? undefined : json['dockerImage'],
        'databaseRootPassword': json['databaseRootPassword'],
        'projectId': json['projectId'],
        'description': json['description'] == null ? undefined : json['description'],
        'databaseName': json['databaseName'],
        'databaseUser': json['databaseUser'],
        'databasePassword': json['databasePassword'],
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
    };
}

export function MariadbCreateRequestToJSON(json: any): MariadbCreateRequest {
    return MariadbCreateRequestToJSONTyped(json, false);
}

export function MariadbCreateRequestToJSONTyped(value?: MariadbCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'appName': value['appName'],
        'dockerImage': value['dockerImage'],
        'databaseRootPassword': value['databaseRootPassword'],
        'projectId': value['projectId'],
        'description': value['description'],
        'databaseName': value['databaseName'],
        'databaseUser': value['databaseUser'],
        'databasePassword': value['databasePassword'],
        'serverId': value['serverId'],
    };
}

