/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MariadbReloadRequest
 */
export interface MariadbReloadRequest {
    /**
     * 
     * @type {string}
     * @memberof MariadbReloadRequest
     */
    mariadbId: string;
    /**
     * 
     * @type {string}
     * @memberof MariadbReloadRequest
     */
    appName: string;
}

/**
 * Check if a given object implements the MariadbReloadRequest interface.
 */
export function instanceOfMariadbReloadRequest(value: object): value is MariadbReloadRequest {
    if (!('mariadbId' in value) || value['mariadbId'] === undefined) return false;
    if (!('appName' in value) || value['appName'] === undefined) return false;
    return true;
}

export function MariadbReloadRequestFromJSON(json: any): MariadbReloadRequest {
    return MariadbReloadRequestFromJSONTyped(json, false);
}

export function MariadbReloadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MariadbReloadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mariadbId': json['mariadbId'],
        'appName': json['appName'],
    };
}

export function MariadbReloadRequestToJSON(json: any): MariadbReloadRequest {
    return MariadbReloadRequestToJSONTyped(json, false);
}

export function MariadbReloadRequestToJSONTyped(value?: MariadbReloadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mariadbId': value['mariadbId'],
        'appName': value['appName'],
    };
}

