/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoSaveEnvironmentRequest
 */
export interface MongoSaveEnvironmentRequest {
    /**
     * 
     * @type {string}
     * @memberof MongoSaveEnvironmentRequest
     */
    mongoId: string;
    /**
     * 
     * @type {string}
     * @memberof MongoSaveEnvironmentRequest
     */
    env?: string | null;
}

/**
 * Check if a given object implements the MongoSaveEnvironmentRequest interface.
 */
export function instanceOfMongoSaveEnvironmentRequest(value: object): value is MongoSaveEnvironmentRequest {
    if (!('mongoId' in value) || value['mongoId'] === undefined) return false;
    return true;
}

export function MongoSaveEnvironmentRequestFromJSON(json: any): MongoSaveEnvironmentRequest {
    return MongoSaveEnvironmentRequestFromJSONTyped(json, false);
}

export function MongoSaveEnvironmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoSaveEnvironmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mongoId': json['mongoId'],
        'env': json['env'] == null ? undefined : json['env'],
    };
}

export function MongoSaveEnvironmentRequestToJSON(json: any): MongoSaveEnvironmentRequest {
    return MongoSaveEnvironmentRequestToJSONTyped(json, false);
}

export function MongoSaveEnvironmentRequestToJSONTyped(value?: MongoSaveEnvironmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mongoId': value['mongoId'],
        'env': value['env'],
    };
}

