/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoChangeStatusRequest
 */
export interface MongoChangeStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof MongoChangeStatusRequest
     */
    mongoId: string;
    /**
     * 
     * @type {string}
     * @memberof MongoChangeStatusRequest
     */
    applicationStatus: MongoChangeStatusRequestApplicationStatusEnum;
}


/**
 * @export
 */
export const MongoChangeStatusRequestApplicationStatusEnum = {
    Idle: 'idle',
    Running: 'running',
    Done: 'done',
    Error: 'error'
} as const;
export type MongoChangeStatusRequestApplicationStatusEnum = typeof MongoChangeStatusRequestApplicationStatusEnum[keyof typeof MongoChangeStatusRequestApplicationStatusEnum];


/**
 * Check if a given object implements the MongoChangeStatusRequest interface.
 */
export function instanceOfMongoChangeStatusRequest(value: object): value is MongoChangeStatusRequest {
    if (!('mongoId' in value) || value['mongoId'] === undefined) return false;
    if (!('applicationStatus' in value) || value['applicationStatus'] === undefined) return false;
    return true;
}

export function MongoChangeStatusRequestFromJSON(json: any): MongoChangeStatusRequest {
    return MongoChangeStatusRequestFromJSONTyped(json, false);
}

export function MongoChangeStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoChangeStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mongoId': json['mongoId'],
        'applicationStatus': json['applicationStatus'],
    };
}

export function MongoChangeStatusRequestToJSON(json: any): MongoChangeStatusRequest {
    return MongoChangeStatusRequestToJSONTyped(json, false);
}

export function MongoChangeStatusRequestToJSONTyped(value?: MongoChangeStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mongoId': value['mongoId'],
        'applicationStatus': value['applicationStatus'],
    };
}

