/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoMoveRequest
 */
export interface MongoMoveRequest {
    /**
     * 
     * @type {string}
     * @memberof MongoMoveRequest
     */
    mongoId: string;
    /**
     * 
     * @type {string}
     * @memberof MongoMoveRequest
     */
    targetProjectId: string;
}

/**
 * Check if a given object implements the MongoMoveRequest interface.
 */
export function instanceOfMongoMoveRequest(value: object): value is MongoMoveRequest {
    if (!('mongoId' in value) || value['mongoId'] === undefined) return false;
    if (!('targetProjectId' in value) || value['targetProjectId'] === undefined) return false;
    return true;
}

export function MongoMoveRequestFromJSON(json: any): MongoMoveRequest {
    return MongoMoveRequestFromJSONTyped(json, false);
}

export function MongoMoveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoMoveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mongoId': json['mongoId'],
        'targetProjectId': json['targetProjectId'],
    };
}

export function MongoMoveRequestToJSON(json: any): MongoMoveRequest {
    return MongoMoveRequestToJSONTyped(json, false);
}

export function MongoMoveRequestToJSONTyped(value?: MongoMoveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mongoId': value['mongoId'],
        'targetProjectId': value['targetProjectId'],
    };
}

