/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MongoStartRequest
 */
export interface MongoStartRequest {
    /**
     * 
     * @type {string}
     * @memberof MongoStartRequest
     */
    mongoId: string;
}

/**
 * Check if a given object implements the MongoStartRequest interface.
 */
export function instanceOfMongoStartRequest(value: object): value is MongoStartRequest {
    if (!('mongoId' in value) || value['mongoId'] === undefined) return false;
    return true;
}

export function MongoStartRequestFromJSON(json: any): MongoStartRequest {
    return MongoStartRequestFromJSONTyped(json, false);
}

export function MongoStartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MongoStartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mongoId': json['mongoId'],
    };
}

export function MongoStartRequestToJSON(json: any): MongoStartRequest {
    return MongoStartRequestToJSONTyped(json, false);
}

export function MongoStartRequestToJSONTyped(value?: MongoStartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mongoId': value['mongoId'],
    };
}

