/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MysqlSaveExternalPortRequest
 */
export interface MysqlSaveExternalPortRequest {
    /**
     * 
     * @type {string}
     * @memberof MysqlSaveExternalPortRequest
     */
    mysqlId: string;
    /**
     * 
     * @type {number}
     * @memberof MysqlSaveExternalPortRequest
     */
    externalPort: number | null;
}

/**
 * Check if a given object implements the MysqlSaveExternalPortRequest interface.
 */
export function instanceOfMysqlSaveExternalPortRequest(value: object): value is MysqlSaveExternalPortRequest {
    if (!('mysqlId' in value) || value['mysqlId'] === undefined) return false;
    if (!('externalPort' in value) || value['externalPort'] === undefined) return false;
    return true;
}

export function MysqlSaveExternalPortRequestFromJSON(json: any): MysqlSaveExternalPortRequest {
    return MysqlSaveExternalPortRequestFromJSONTyped(json, false);
}

export function MysqlSaveExternalPortRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MysqlSaveExternalPortRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mysqlId': json['mysqlId'],
        'externalPort': json['externalPort'],
    };
}

export function MysqlSaveExternalPortRequestToJSON(json: any): MysqlSaveExternalPortRequest {
    return MysqlSaveExternalPortRequestToJSONTyped(json, false);
}

export function MysqlSaveExternalPortRequestToJSONTyped(value?: MysqlSaveExternalPortRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mysqlId': value['mysqlId'],
        'externalPort': value['externalPort'],
    };
}

