/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationTestGotifyConnectionRequest
 */
export interface NotificationTestGotifyConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationTestGotifyConnectionRequest
     */
    serverUrl: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationTestGotifyConnectionRequest
     */
    appToken: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationTestGotifyConnectionRequest
     */
    priority: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationTestGotifyConnectionRequest
     */
    decoration?: boolean;
}

/**
 * Check if a given object implements the NotificationTestGotifyConnectionRequest interface.
 */
export function instanceOfNotificationTestGotifyConnectionRequest(value: object): value is NotificationTestGotifyConnectionRequest {
    if (!('serverUrl' in value) || value['serverUrl'] === undefined) return false;
    if (!('appToken' in value) || value['appToken'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function NotificationTestGotifyConnectionRequestFromJSON(json: any): NotificationTestGotifyConnectionRequest {
    return NotificationTestGotifyConnectionRequestFromJSONTyped(json, false);
}

export function NotificationTestGotifyConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationTestGotifyConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serverUrl': json['serverUrl'],
        'appToken': json['appToken'],
        'priority': json['priority'],
        'decoration': json['decoration'] == null ? undefined : json['decoration'],
    };
}

export function NotificationTestGotifyConnectionRequestToJSON(json: any): NotificationTestGotifyConnectionRequest {
    return NotificationTestGotifyConnectionRequestToJSONTyped(json, false);
}

export function NotificationTestGotifyConnectionRequestToJSONTyped(value?: NotificationTestGotifyConnectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverUrl': value['serverUrl'],
        'appToken': value['appToken'],
        'priority': value['priority'],
        'decoration': value['decoration'],
    };
}

