/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationUpdateTelegramRequest
 */
export interface NotificationUpdateTelegramRequest {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateTelegramRequest
     */
    appBuildError?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateTelegramRequest
     */
    databaseBackup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateTelegramRequest
     */
    dokployRestart?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateTelegramRequest
     */
    appDeploy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateTelegramRequest
     */
    dockerCleanup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateTelegramRequest
     */
    serverThreshold?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    botToken?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    chatId?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    messageThreadId?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    notificationId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    telegramId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateTelegramRequest
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the NotificationUpdateTelegramRequest interface.
 */
export function instanceOfNotificationUpdateTelegramRequest(value: object): value is NotificationUpdateTelegramRequest {
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    if (!('telegramId' in value) || value['telegramId'] === undefined) return false;
    return true;
}

export function NotificationUpdateTelegramRequestFromJSON(json: any): NotificationUpdateTelegramRequest {
    return NotificationUpdateTelegramRequestFromJSONTyped(json, false);
}

export function NotificationUpdateTelegramRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationUpdateTelegramRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appBuildError': json['appBuildError'] == null ? undefined : json['appBuildError'],
        'databaseBackup': json['databaseBackup'] == null ? undefined : json['databaseBackup'],
        'dokployRestart': json['dokployRestart'] == null ? undefined : json['dokployRestart'],
        'name': json['name'] == null ? undefined : json['name'],
        'appDeploy': json['appDeploy'] == null ? undefined : json['appDeploy'],
        'dockerCleanup': json['dockerCleanup'] == null ? undefined : json['dockerCleanup'],
        'serverThreshold': json['serverThreshold'] == null ? undefined : json['serverThreshold'],
        'botToken': json['botToken'] == null ? undefined : json['botToken'],
        'chatId': json['chatId'] == null ? undefined : json['chatId'],
        'messageThreadId': json['messageThreadId'] == null ? undefined : json['messageThreadId'],
        'notificationId': json['notificationId'],
        'telegramId': json['telegramId'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function NotificationUpdateTelegramRequestToJSON(json: any): NotificationUpdateTelegramRequest {
    return NotificationUpdateTelegramRequestToJSONTyped(json, false);
}

export function NotificationUpdateTelegramRequestToJSONTyped(value?: NotificationUpdateTelegramRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appBuildError': value['appBuildError'],
        'databaseBackup': value['databaseBackup'],
        'dokployRestart': value['dokployRestart'],
        'name': value['name'],
        'appDeploy': value['appDeploy'],
        'dockerCleanup': value['dockerCleanup'],
        'serverThreshold': value['serverThreshold'],
        'botToken': value['botToken'],
        'chatId': value['chatId'],
        'messageThreadId': value['messageThreadId'],
        'notificationId': value['notificationId'],
        'telegramId': value['telegramId'],
        'organizationId': value['organizationId'],
    };
}

