/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationTestTelegramConnectionRequest
 */
export interface NotificationTestTelegramConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof NotificationTestTelegramConnectionRequest
     */
    botToken: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationTestTelegramConnectionRequest
     */
    chatId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationTestTelegramConnectionRequest
     */
    messageThreadId: string;
}

/**
 * Check if a given object implements the NotificationTestTelegramConnectionRequest interface.
 */
export function instanceOfNotificationTestTelegramConnectionRequest(value: object): value is NotificationTestTelegramConnectionRequest {
    if (!('botToken' in value) || value['botToken'] === undefined) return false;
    if (!('chatId' in value) || value['chatId'] === undefined) return false;
    if (!('messageThreadId' in value) || value['messageThreadId'] === undefined) return false;
    return true;
}

export function NotificationTestTelegramConnectionRequestFromJSON(json: any): NotificationTestTelegramConnectionRequest {
    return NotificationTestTelegramConnectionRequestFromJSONTyped(json, false);
}

export function NotificationTestTelegramConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationTestTelegramConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'botToken': json['botToken'],
        'chatId': json['chatId'],
        'messageThreadId': json['messageThreadId'],
    };
}

export function NotificationTestTelegramConnectionRequestToJSON(json: any): NotificationTestTelegramConnectionRequest {
    return NotificationTestTelegramConnectionRequestToJSONTyped(json, false);
}

export function NotificationTestTelegramConnectionRequestToJSONTyped(value?: NotificationTestTelegramConnectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'botToken': value['botToken'],
        'chatId': value['chatId'],
        'messageThreadId': value['messageThreadId'],
    };
}

