/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationUpdateGotifyRequest
 */
export interface NotificationUpdateGotifyRequest {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateGotifyRequest
     */
    appBuildError?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateGotifyRequest
     */
    databaseBackup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateGotifyRequest
     */
    dokployRestart?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateGotifyRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateGotifyRequest
     */
    appDeploy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateGotifyRequest
     */
    dockerCleanup?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateGotifyRequest
     */
    serverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateGotifyRequest
     */
    appToken?: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationUpdateGotifyRequest
     */
    priority?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationUpdateGotifyRequest
     */
    decoration?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateGotifyRequest
     */
    notificationId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateGotifyRequest
     */
    gotifyId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateGotifyRequest
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the NotificationUpdateGotifyRequest interface.
 */
export function instanceOfNotificationUpdateGotifyRequest(value: object): value is NotificationUpdateGotifyRequest {
    if (!('notificationId' in value) || value['notificationId'] === undefined) return false;
    if (!('gotifyId' in value) || value['gotifyId'] === undefined) return false;
    return true;
}

export function NotificationUpdateGotifyRequestFromJSON(json: any): NotificationUpdateGotifyRequest {
    return NotificationUpdateGotifyRequestFromJSONTyped(json, false);
}

export function NotificationUpdateGotifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationUpdateGotifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appBuildError': json['appBuildError'] == null ? undefined : json['appBuildError'],
        'databaseBackup': json['databaseBackup'] == null ? undefined : json['databaseBackup'],
        'dokployRestart': json['dokployRestart'] == null ? undefined : json['dokployRestart'],
        'name': json['name'] == null ? undefined : json['name'],
        'appDeploy': json['appDeploy'] == null ? undefined : json['appDeploy'],
        'dockerCleanup': json['dockerCleanup'] == null ? undefined : json['dockerCleanup'],
        'serverUrl': json['serverUrl'] == null ? undefined : json['serverUrl'],
        'appToken': json['appToken'] == null ? undefined : json['appToken'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'decoration': json['decoration'] == null ? undefined : json['decoration'],
        'notificationId': json['notificationId'],
        'gotifyId': json['gotifyId'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function NotificationUpdateGotifyRequestToJSON(json: any): NotificationUpdateGotifyRequest {
    return NotificationUpdateGotifyRequestToJSONTyped(json, false);
}

export function NotificationUpdateGotifyRequestToJSONTyped(value?: NotificationUpdateGotifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appBuildError': value['appBuildError'],
        'databaseBackup': value['databaseBackup'],
        'dokployRestart': value['dokployRestart'],
        'name': value['name'],
        'appDeploy': value['appDeploy'],
        'dockerCleanup': value['dockerCleanup'],
        'serverUrl': value['serverUrl'],
        'appToken': value['appToken'],
        'priority': value['priority'],
        'decoration': value['decoration'],
        'notificationId': value['notificationId'],
        'gotifyId': value['gotifyId'],
        'organizationId': value['organizationId'],
    };
}

