/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUpdateRequest
 */
export interface OrganizationUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateRequest
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUpdateRequest
     */
    logo?: string;
}

/**
 * Check if a given object implements the OrganizationUpdateRequest interface.
 */
export function instanceOfOrganizationUpdateRequest(value: object): value is OrganizationUpdateRequest {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationUpdateRequestFromJSON(json: any): OrganizationUpdateRequest {
    return OrganizationUpdateRequestFromJSONTyped(json, false);
}

export function OrganizationUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'],
        'name': json['name'],
        'logo': json['logo'] == null ? undefined : json['logo'],
    };
}

export function OrganizationUpdateRequestToJSON(json: any): OrganizationUpdateRequest {
    return OrganizationUpdateRequestToJSONTyped(json, false);
}

export function OrganizationUpdateRequestToJSONTyped(value?: OrganizationUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organizationId': value['organizationId'],
        'name': value['name'],
        'logo': value['logo'],
    };
}

