/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationRemoveInvitationRequest
 */
export interface OrganizationRemoveInvitationRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationRemoveInvitationRequest
     */
    invitationId: string;
}

/**
 * Check if a given object implements the OrganizationRemoveInvitationRequest interface.
 */
export function instanceOfOrganizationRemoveInvitationRequest(value: object): value is OrganizationRemoveInvitationRequest {
    if (!('invitationId' in value) || value['invitationId'] === undefined) return false;
    return true;
}

export function OrganizationRemoveInvitationRequestFromJSON(json: any): OrganizationRemoveInvitationRequest {
    return OrganizationRemoveInvitationRequestFromJSONTyped(json, false);
}

export function OrganizationRemoveInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationRemoveInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invitationId': json['invitationId'],
    };
}

export function OrganizationRemoveInvitationRequestToJSON(json: any): OrganizationRemoveInvitationRequest {
    return OrganizationRemoveInvitationRequestToJSONTyped(json, false);
}

export function OrganizationRemoveInvitationRequestToJSONTyped(value?: OrganizationRemoveInvitationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invitationId': value['invitationId'],
    };
}

