/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortCreateRequest
 */
export interface PortCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof PortCreateRequest
     */
    publishedPort: number;
    /**
     * 
     * @type {number}
     * @memberof PortCreateRequest
     */
    targetPort: number;
    /**
     * 
     * @type {string}
     * @memberof PortCreateRequest
     */
    protocol?: PortCreateRequestProtocolEnum;
    /**
     * 
     * @type {string}
     * @memberof PortCreateRequest
     */
    applicationId: string;
}


/**
 * @export
 */
export const PortCreateRequestProtocolEnum = {
    Tcp: 'tcp',
    Udp: 'udp'
} as const;
export type PortCreateRequestProtocolEnum = typeof PortCreateRequestProtocolEnum[keyof typeof PortCreateRequestProtocolEnum];


/**
 * Check if a given object implements the PortCreateRequest interface.
 */
export function instanceOfPortCreateRequest(value: object): value is PortCreateRequest {
    if (!('publishedPort' in value) || value['publishedPort'] === undefined) return false;
    if (!('targetPort' in value) || value['targetPort'] === undefined) return false;
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    return true;
}

export function PortCreateRequestFromJSON(json: any): PortCreateRequest {
    return PortCreateRequestFromJSONTyped(json, false);
}

export function PortCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'publishedPort': json['publishedPort'],
        'targetPort': json['targetPort'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'applicationId': json['applicationId'],
    };
}

export function PortCreateRequestToJSON(json: any): PortCreateRequest {
    return PortCreateRequestToJSONTyped(json, false);
}

export function PortCreateRequestToJSONTyped(value?: PortCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publishedPort': value['publishedPort'],
        'targetPort': value['targetPort'],
        'protocol': value['protocol'],
        'applicationId': value['applicationId'],
    };
}

