/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostgresMoveRequest
 */
export interface PostgresMoveRequest {
    /**
     * 
     * @type {string}
     * @memberof PostgresMoveRequest
     */
    postgresId: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresMoveRequest
     */
    targetProjectId: string;
}

/**
 * Check if a given object implements the PostgresMoveRequest interface.
 */
export function instanceOfPostgresMoveRequest(value: object): value is PostgresMoveRequest {
    if (!('postgresId' in value) || value['postgresId'] === undefined) return false;
    if (!('targetProjectId' in value) || value['targetProjectId'] === undefined) return false;
    return true;
}

export function PostgresMoveRequestFromJSON(json: any): PostgresMoveRequest {
    return PostgresMoveRequestFromJSONTyped(json, false);
}

export function PostgresMoveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostgresMoveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'postgresId': json['postgresId'],
        'targetProjectId': json['targetProjectId'],
    };
}

export function PostgresMoveRequestToJSON(json: any): PostgresMoveRequest {
    return PostgresMoveRequestToJSONTyped(json, false);
}

export function PostgresMoveRequestToJSONTyped(value?: PostgresMoveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postgresId': value['postgresId'],
        'targetProjectId': value['targetProjectId'],
    };
}

