/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostgresUpdateRequest
 */
export interface PostgresUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    postgresId: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    appName?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    databaseName?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    databaseUser?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    databasePassword?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    dockerImage?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    command?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    env?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    memoryReservation?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PostgresUpdateRequest
     */
    externalPort?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    memoryLimit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    cpuReservation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    cpuLimit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    applicationStatus?: PostgresUpdateRequestApplicationStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PostgresUpdateRequest
     */
    projectId?: string;
}


/**
 * @export
 */
export const PostgresUpdateRequestApplicationStatusEnum = {
    Idle: 'idle',
    Running: 'running',
    Done: 'done',
    Error: 'error'
} as const;
export type PostgresUpdateRequestApplicationStatusEnum = typeof PostgresUpdateRequestApplicationStatusEnum[keyof typeof PostgresUpdateRequestApplicationStatusEnum];


/**
 * Check if a given object implements the PostgresUpdateRequest interface.
 */
export function instanceOfPostgresUpdateRequest(value: object): value is PostgresUpdateRequest {
    if (!('postgresId' in value) || value['postgresId'] === undefined) return false;
    return true;
}

export function PostgresUpdateRequestFromJSON(json: any): PostgresUpdateRequest {
    return PostgresUpdateRequestFromJSONTyped(json, false);
}

export function PostgresUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostgresUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'postgresId': json['postgresId'],
        'name': json['name'] == null ? undefined : json['name'],
        'appName': json['appName'] == null ? undefined : json['appName'],
        'databaseName': json['databaseName'] == null ? undefined : json['databaseName'],
        'databaseUser': json['databaseUser'] == null ? undefined : json['databaseUser'],
        'databasePassword': json['databasePassword'] == null ? undefined : json['databasePassword'],
        'description': json['description'] == null ? undefined : json['description'],
        'dockerImage': json['dockerImage'] == null ? undefined : json['dockerImage'],
        'command': json['command'] == null ? undefined : json['command'],
        'env': json['env'] == null ? undefined : json['env'],
        'memoryReservation': json['memoryReservation'] == null ? undefined : json['memoryReservation'],
        'externalPort': json['externalPort'] == null ? undefined : json['externalPort'],
        'memoryLimit': json['memoryLimit'] == null ? undefined : json['memoryLimit'],
        'cpuReservation': json['cpuReservation'] == null ? undefined : json['cpuReservation'],
        'cpuLimit': json['cpuLimit'] == null ? undefined : json['cpuLimit'],
        'applicationStatus': json['applicationStatus'] == null ? undefined : json['applicationStatus'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function PostgresUpdateRequestToJSON(json: any): PostgresUpdateRequest {
    return PostgresUpdateRequestToJSONTyped(json, false);
}

export function PostgresUpdateRequestToJSONTyped(value?: PostgresUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postgresId': value['postgresId'],
        'name': value['name'],
        'appName': value['appName'],
        'databaseName': value['databaseName'],
        'databaseUser': value['databaseUser'],
        'databasePassword': value['databasePassword'],
        'description': value['description'],
        'dockerImage': value['dockerImage'],
        'command': value['command'],
        'env': value['env'],
        'memoryReservation': value['memoryReservation'],
        'externalPort': value['externalPort'],
        'memoryLimit': value['memoryLimit'],
        'cpuReservation': value['cpuReservation'],
        'cpuLimit': value['cpuLimit'],
        'applicationStatus': value['applicationStatus'],
        'createdAt': value['createdAt'],
        'projectId': value['projectId'],
    };
}

