/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreviewDeploymentDeleteRequest
 */
export interface PreviewDeploymentDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof PreviewDeploymentDeleteRequest
     */
    previewDeploymentId: string;
}

/**
 * Check if a given object implements the PreviewDeploymentDeleteRequest interface.
 */
export function instanceOfPreviewDeploymentDeleteRequest(value: object): value is PreviewDeploymentDeleteRequest {
    if (!('previewDeploymentId' in value) || value['previewDeploymentId'] === undefined) return false;
    return true;
}

export function PreviewDeploymentDeleteRequestFromJSON(json: any): PreviewDeploymentDeleteRequest {
    return PreviewDeploymentDeleteRequestFromJSONTyped(json, false);
}

export function PreviewDeploymentDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewDeploymentDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'previewDeploymentId': json['previewDeploymentId'],
    };
}

export function PreviewDeploymentDeleteRequestToJSON(json: any): PreviewDeploymentDeleteRequest {
    return PreviewDeploymentDeleteRequestToJSONTyped(json, false);
}

export function PreviewDeploymentDeleteRequestToJSONTyped(value?: PreviewDeploymentDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'previewDeploymentId': value['previewDeploymentId'],
    };
}

