/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RedirectsDeleteRequest
 */
export interface RedirectsDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof RedirectsDeleteRequest
     */
    redirectId: string;
}

/**
 * Check if a given object implements the RedirectsDeleteRequest interface.
 */
export function instanceOfRedirectsDeleteRequest(value: object): value is RedirectsDeleteRequest {
    if (!('redirectId' in value) || value['redirectId'] === undefined) return false;
    return true;
}

export function RedirectsDeleteRequestFromJSON(json: any): RedirectsDeleteRequest {
    return RedirectsDeleteRequestFromJSONTyped(json, false);
}

export function RedirectsDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectsDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectId': json['redirectId'],
    };
}

export function RedirectsDeleteRequestToJSON(json: any): RedirectsDeleteRequest {
    return RedirectsDeleteRequestToJSONTyped(json, false);
}

export function RedirectsDeleteRequestToJSONTyped(value?: RedirectsDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirectId': value['redirectId'],
    };
}

