/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleDeleteRequest
 */
export interface ScheduleDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof ScheduleDeleteRequest
     */
    scheduleId: string;
}

/**
 * Check if a given object implements the ScheduleDeleteRequest interface.
 */
export function instanceOfScheduleDeleteRequest(value: object): value is ScheduleDeleteRequest {
    if (!('scheduleId' in value) || value['scheduleId'] === undefined) return false;
    return true;
}

export function ScheduleDeleteRequestFromJSON(json: any): ScheduleDeleteRequest {
    return ScheduleDeleteRequestFromJSONTyped(json, false);
}

export function ScheduleDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleId': json['scheduleId'],
    };
}

export function ScheduleDeleteRequestToJSON(json: any): ScheduleDeleteRequest {
    return ScheduleDeleteRequestToJSONTyped(json, false);
}

export function ScheduleDeleteRequestToJSONTyped(value?: ScheduleDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scheduleId': value['scheduleId'],
    };
}

