/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityDeleteRequest
 */
export interface SecurityDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof SecurityDeleteRequest
     */
    securityId: string;
}

/**
 * Check if a given object implements the SecurityDeleteRequest interface.
 */
export function instanceOfSecurityDeleteRequest(value: object): value is SecurityDeleteRequest {
    if (!('securityId' in value) || value['securityId'] === undefined) return false;
    return true;
}

export function SecurityDeleteRequestFromJSON(json: any): SecurityDeleteRequest {
    return SecurityDeleteRequestFromJSONTyped(json, false);
}

export function SecurityDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'securityId': json['securityId'],
    };
}

export function SecurityDeleteRequestToJSON(json: any): SecurityDeleteRequest {
    return SecurityDeleteRequestToJSONTyped(json, false);
}

export function SecurityDeleteRequestToJSONTyped(value?: SecurityDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'securityId': value['securityId'],
    };
}

