/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecurityCreateRequest
 */
export interface SecurityCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof SecurityCreateRequest
     */
    applicationId: string;
    /**
     * 
     * @type {string}
     * @memberof SecurityCreateRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof SecurityCreateRequest
     */
    password: string;
}

/**
 * Check if a given object implements the SecurityCreateRequest interface.
 */
export function instanceOfSecurityCreateRequest(value: object): value is SecurityCreateRequest {
    if (!('applicationId' in value) || value['applicationId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SecurityCreateRequestFromJSON(json: any): SecurityCreateRequest {
    return SecurityCreateRequestFromJSONTyped(json, false);
}

export function SecurityCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'applicationId': json['applicationId'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function SecurityCreateRequestToJSON(json: any): SecurityCreateRequest {
    return SecurityCreateRequestToJSONTyped(json, false);
}

export function SecurityCreateRequestToJSONTyped(value?: SecurityCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'applicationId': value['applicationId'],
        'username': value['username'],
        'password': value['password'],
    };
}

