/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsToggleDashboardRequest
 */
export interface SettingsToggleDashboardRequest {
    /**
     * 
     * @type {boolean}
     * @memberof SettingsToggleDashboardRequest
     */
    enableDashboard?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingsToggleDashboardRequest
     */
    serverId?: string;
}

/**
 * Check if a given object implements the SettingsToggleDashboardRequest interface.
 */
export function instanceOfSettingsToggleDashboardRequest(value: object): value is SettingsToggleDashboardRequest {
    return true;
}

export function SettingsToggleDashboardRequestFromJSON(json: any): SettingsToggleDashboardRequest {
    return SettingsToggleDashboardRequestFromJSONTyped(json, false);
}

export function SettingsToggleDashboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsToggleDashboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enableDashboard': json['enableDashboard'] == null ? undefined : json['enableDashboard'],
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
    };
}

export function SettingsToggleDashboardRequestToJSON(json: any): SettingsToggleDashboardRequest {
    return SettingsToggleDashboardRequestToJSONTyped(json, false);
}

export function SettingsToggleDashboardRequestToJSONTyped(value?: SettingsToggleDashboardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enableDashboard': value['enableDashboard'],
        'serverId': value['serverId'],
    };
}

