/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsUpdateTraefikFileRequest
 */
export interface SettingsUpdateTraefikFileRequest {
    /**
     * 
     * @type {string}
     * @memberof SettingsUpdateTraefikFileRequest
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsUpdateTraefikFileRequest
     */
    traefikConfig: string;
    /**
     * 
     * @type {string}
     * @memberof SettingsUpdateTraefikFileRequest
     */
    serverId?: string;
}

/**
 * Check if a given object implements the SettingsUpdateTraefikFileRequest interface.
 */
export function instanceOfSettingsUpdateTraefikFileRequest(value: object): value is SettingsUpdateTraefikFileRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('traefikConfig' in value) || value['traefikConfig'] === undefined) return false;
    return true;
}

export function SettingsUpdateTraefikFileRequestFromJSON(json: any): SettingsUpdateTraefikFileRequest {
    return SettingsUpdateTraefikFileRequestFromJSONTyped(json, false);
}

export function SettingsUpdateTraefikFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsUpdateTraefikFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'traefikConfig': json['traefikConfig'],
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
    };
}

export function SettingsUpdateTraefikFileRequestToJSON(json: any): SettingsUpdateTraefikFileRequest {
    return SettingsUpdateTraefikFileRequestToJSONTyped(json, false);
}

export function SettingsUpdateTraefikFileRequestToJSONTyped(value?: SettingsUpdateTraefikFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'traefikConfig': value['traefikConfig'],
        'serverId': value['serverId'],
    };
}

