/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SettingsUpdateTraefikPortsRequestAdditionalPortsInner } from './SettingsUpdateTraefikPortsRequestAdditionalPortsInner';
import {
    SettingsUpdateTraefikPortsRequestAdditionalPortsInnerFromJSON,
    SettingsUpdateTraefikPortsRequestAdditionalPortsInnerFromJSONTyped,
    SettingsUpdateTraefikPortsRequestAdditionalPortsInnerToJSON,
    SettingsUpdateTraefikPortsRequestAdditionalPortsInnerToJSONTyped,
} from './SettingsUpdateTraefikPortsRequestAdditionalPortsInner';

/**
 * 
 * @export
 * @interface SettingsUpdateTraefikPortsRequest
 */
export interface SettingsUpdateTraefikPortsRequest {
    /**
     * 
     * @type {string}
     * @memberof SettingsUpdateTraefikPortsRequest
     */
    serverId?: string;
    /**
     * 
     * @type {Array<SettingsUpdateTraefikPortsRequestAdditionalPortsInner>}
     * @memberof SettingsUpdateTraefikPortsRequest
     */
    additionalPorts: Array<SettingsUpdateTraefikPortsRequestAdditionalPortsInner>;
}

/**
 * Check if a given object implements the SettingsUpdateTraefikPortsRequest interface.
 */
export function instanceOfSettingsUpdateTraefikPortsRequest(value: object): value is SettingsUpdateTraefikPortsRequest {
    if (!('additionalPorts' in value) || value['additionalPorts'] === undefined) return false;
    return true;
}

export function SettingsUpdateTraefikPortsRequestFromJSON(json: any): SettingsUpdateTraefikPortsRequest {
    return SettingsUpdateTraefikPortsRequestFromJSONTyped(json, false);
}

export function SettingsUpdateTraefikPortsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsUpdateTraefikPortsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serverId': json['serverId'] == null ? undefined : json['serverId'],
        'additionalPorts': ((json['additionalPorts'] as Array<any>).map(SettingsUpdateTraefikPortsRequestAdditionalPortsInnerFromJSON)),
    };
}

export function SettingsUpdateTraefikPortsRequestToJSON(json: any): SettingsUpdateTraefikPortsRequest {
    return SettingsUpdateTraefikPortsRequestToJSONTyped(json, false);
}

export function SettingsUpdateTraefikPortsRequestToJSONTyped(value?: SettingsUpdateTraefikPortsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serverId': value['serverId'],
        'additionalPorts': ((value['additionalPorts'] as Array<any>).map(SettingsUpdateTraefikPortsRequestAdditionalPortsInnerToJSON)),
    };
}

