/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SshKeyGenerateRequest
 */
export interface SshKeyGenerateRequest {
    /**
     * 
     * @type {string}
     * @memberof SshKeyGenerateRequest
     */
    type?: SshKeyGenerateRequestTypeEnum;
}


/**
 * @export
 */
export const SshKeyGenerateRequestTypeEnum = {
    Rsa: 'rsa',
    Ed25519: 'ed25519'
} as const;
export type SshKeyGenerateRequestTypeEnum = typeof SshKeyGenerateRequestTypeEnum[keyof typeof SshKeyGenerateRequestTypeEnum];


/**
 * Check if a given object implements the SshKeyGenerateRequest interface.
 */
export function instanceOfSshKeyGenerateRequest(value: object): value is SshKeyGenerateRequest {
    return true;
}

export function SshKeyGenerateRequestFromJSON(json: any): SshKeyGenerateRequest {
    return SshKeyGenerateRequestFromJSONTyped(json, false);
}

export function SshKeyGenerateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshKeyGenerateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SshKeyGenerateRequestToJSON(json: any): SshKeyGenerateRequest {
    return SshKeyGenerateRequestToJSONTyped(json, false);
}

export function SshKeyGenerateRequestToJSONTyped(value?: SshKeyGenerateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

