/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeCreateCheckoutSessionRequest
 */
export interface StripeCreateCheckoutSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof StripeCreateCheckoutSessionRequest
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof StripeCreateCheckoutSessionRequest
     */
    serverQuantity: number;
    /**
     * 
     * @type {boolean}
     * @memberof StripeCreateCheckoutSessionRequest
     */
    isAnnual: boolean;
}

/**
 * Check if a given object implements the StripeCreateCheckoutSessionRequest interface.
 */
export function instanceOfStripeCreateCheckoutSessionRequest(value: object): value is StripeCreateCheckoutSessionRequest {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('serverQuantity' in value) || value['serverQuantity'] === undefined) return false;
    if (!('isAnnual' in value) || value['isAnnual'] === undefined) return false;
    return true;
}

export function StripeCreateCheckoutSessionRequestFromJSON(json: any): StripeCreateCheckoutSessionRequest {
    return StripeCreateCheckoutSessionRequestFromJSONTyped(json, false);
}

export function StripeCreateCheckoutSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCreateCheckoutSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'serverQuantity': json['serverQuantity'],
        'isAnnual': json['isAnnual'],
    };
}

export function StripeCreateCheckoutSessionRequestToJSON(json: any): StripeCreateCheckoutSessionRequest {
    return StripeCreateCheckoutSessionRequestToJSONTyped(json, false);
}

export function StripeCreateCheckoutSessionRequestToJSONTyped(value?: StripeCreateCheckoutSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'serverQuantity': value['serverQuantity'],
        'isAnnual': value['isAnnual'],
    };
}

