/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDeleteApiKeyRequest
 */
export interface UserDeleteApiKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof UserDeleteApiKeyRequest
     */
    apiKeyId: string;
}

/**
 * Check if a given object implements the UserDeleteApiKeyRequest interface.
 */
export function instanceOfUserDeleteApiKeyRequest(value: object): value is UserDeleteApiKeyRequest {
    if (!('apiKeyId' in value) || value['apiKeyId'] === undefined) return false;
    return true;
}

export function UserDeleteApiKeyRequestFromJSON(json: any): UserDeleteApiKeyRequest {
    return UserDeleteApiKeyRequestFromJSONTyped(json, false);
}

export function UserDeleteApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDeleteApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKeyId': json['apiKeyId'],
    };
}

export function UserDeleteApiKeyRequestToJSON(json: any): UserDeleteApiKeyRequest {
    return UserDeleteApiKeyRequestToJSONTyped(json, false);
}

export function UserDeleteApiKeyRequestToJSONTyped(value?: UserDeleteApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apiKeyId': value['apiKeyId'],
    };
}

