/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateRequestMetricsConfigServerThresholds
 */
export interface UserUpdateRequestMetricsConfigServerThresholds {
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestMetricsConfigServerThresholds
     */
    cpu: number;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestMetricsConfigServerThresholds
     */
    memory: number;
}

/**
 * Check if a given object implements the UserUpdateRequestMetricsConfigServerThresholds interface.
 */
export function instanceOfUserUpdateRequestMetricsConfigServerThresholds(value: object): value is UserUpdateRequestMetricsConfigServerThresholds {
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    return true;
}

export function UserUpdateRequestMetricsConfigServerThresholdsFromJSON(json: any): UserUpdateRequestMetricsConfigServerThresholds {
    return UserUpdateRequestMetricsConfigServerThresholdsFromJSONTyped(json, false);
}

export function UserUpdateRequestMetricsConfigServerThresholdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRequestMetricsConfigServerThresholds {
    if (json == null) {
        return json;
    }
    return {
        
        'cpu': json['cpu'],
        'memory': json['memory'],
    };
}

export function UserUpdateRequestMetricsConfigServerThresholdsToJSON(json: any): UserUpdateRequestMetricsConfigServerThresholds {
    return UserUpdateRequestMetricsConfigServerThresholdsToJSONTyped(json, false);
}

export function UserUpdateRequestMetricsConfigServerThresholdsToJSONTyped(value?: UserUpdateRequestMetricsConfigServerThresholds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu': value['cpu'],
        'memory': value['memory'],
    };
}

