/* tslint:disable */
/* eslint-disable */
/**
 * Dokploy API
 * Endpoints for dokploy
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserUpdateRequestMetricsConfigContainersServices } from './UserUpdateRequestMetricsConfigContainersServices';
import {
    UserUpdateRequestMetricsConfigContainersServicesFromJSON,
    UserUpdateRequestMetricsConfigContainersServicesFromJSONTyped,
    UserUpdateRequestMetricsConfigContainersServicesToJSON,
    UserUpdateRequestMetricsConfigContainersServicesToJSONTyped,
} from './UserUpdateRequestMetricsConfigContainersServices';

/**
 * 
 * @export
 * @interface UserUpdateRequestMetricsConfigContainers
 */
export interface UserUpdateRequestMetricsConfigContainers {
    /**
     * 
     * @type {number}
     * @memberof UserUpdateRequestMetricsConfigContainers
     */
    refreshRate: number;
    /**
     * 
     * @type {UserUpdateRequestMetricsConfigContainersServices}
     * @memberof UserUpdateRequestMetricsConfigContainers
     */
    services: UserUpdateRequestMetricsConfigContainersServices;
}

/**
 * Check if a given object implements the UserUpdateRequestMetricsConfigContainers interface.
 */
export function instanceOfUserUpdateRequestMetricsConfigContainers(value: object): value is UserUpdateRequestMetricsConfigContainers {
    if (!('refreshRate' in value) || value['refreshRate'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    return true;
}

export function UserUpdateRequestMetricsConfigContainersFromJSON(json: any): UserUpdateRequestMetricsConfigContainers {
    return UserUpdateRequestMetricsConfigContainersFromJSONTyped(json, false);
}

export function UserUpdateRequestMetricsConfigContainersFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateRequestMetricsConfigContainers {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshRate': json['refreshRate'],
        'services': UserUpdateRequestMetricsConfigContainersServicesFromJSON(json['services']),
    };
}

export function UserUpdateRequestMetricsConfigContainersToJSON(json: any): UserUpdateRequestMetricsConfigContainers {
    return UserUpdateRequestMetricsConfigContainersToJSONTyped(json, false);
}

export function UserUpdateRequestMetricsConfigContainersToJSONTyped(value?: UserUpdateRequestMetricsConfigContainers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refreshRate': value['refreshRate'],
        'services': UserUpdateRequestMetricsConfigContainersServicesToJSON(value['services']),
    };
}

